### ISSUE TITLE
C4 Version possible?

### ISSUE THREAD

**Issue by con2net** [timgatzky/form_google_recaptcha#1]
I would love to get this running under C4. Any chance to get an "official C4" Version? Or maybe some hints how we can use this under C4? I tried to copy the package but this hasn´t worked.

**Comment by timgatzky** [comment]
https://github.com/timgatzky/form_google_recaptcha/issues/2

Juhu Stefan, lange ist's her. Aber ich glaube es gibt keine guten Alternativen mehr.
